[package]
name = "zel"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zel"
path = "src/main.rs"

[dependencies]
cranelift = { version = "0.117.2", features = ["module", "native", "object"] }
